name: Deploy Update DB Lambda
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STAGE: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Preload Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build and Push
        shell: bash
        env:
          IAM_ROLE_ARN: ${{ secrets.LAMBDA_ARN }}
          QUEUE_NAME: ${{ secrets.QUEUE_NAME_DEV }}
          S3_BUCKET: ${{ secrets.S3_TMP_BUCKET }}
        run: |
          # Make .env file
          echo "IAM_ROLE_ARN=$IAM_ROLE_ARN" >> .env
          echo "QUEUE_NAME=$QUEUE_NAME" >> .env
          echo "S3_BUCKET=$S3_BUCKET" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

          pip install -r requirements.txt
          python deploy.py --stage=dev_v1

      - name: Deploy Alarm
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: C05NYKY1KS6
          author_name: Github Action
          fields: repo,commit,message,author,took,workflow
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
